In [1]:
print("hi my name is soldier boy.")

hi my name is soldier boy.


In [5]:
#import numpy library
import numpy as np
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[9,7,6,5,4]
arr1=np.array([lst1,lst2,lst3])
print(arr1)
print(arr1.shape)
print(type(arr1))
print(type(lst1))

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 5 4]]
(3, 5)
<class 'numpy.ndarray'>
<class 'list'>


##Numpy Full name is Numerical Python